version: '3.8'
services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: bestchatpassword
      POSTGRES_DB: bestchat-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
